In [22]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
import random 

DATADIR = "Data/Train/"
CATEGORIES = ["Image","Background","Partial"]
def create_training_data():
    Training_Data = []
    img_size = 50
    X = []
    y = []
    for categories in CATEGORIES:
        Path = os.path.join(DATADIR,categories) # gives the path to the images; Data/Train/Image or Background
        print(Path)
        class_num = CATEGORIES.index(categories) # numbers the classes
        print(class_num)
        try:
            for img in os.listdir(Path): #gives the images from the path
                img_array = cv2.imread(os.path.join(Path,img),cv2.IMREAD_GRAYSCALE) 
                Training_Data.append([img_array,class_num])
                #plt.imshow(img_array,cmap='gray')
                #plt.show()
                #break
        except Exception as e:
            pass
    random.shuffle(Training_Data) # do it before conversion to array as list is mutable
    
    for features,labels in Training_Data:
        X.append(features)
        y.append(labels)
    
    X = np.array(X).reshape(-1,img_size,img_size,1) # converts it to arrays with shape (number of images,dim of image)
    y = np.array(y)
    X = X/255.0 # this is normaalization of only the images
    
    #print(y[5])
    return X,y

X,y = create_training_data()


Data/Train/Image
0
Data/Train/Background
1
Data/Train/Partial
2


In [23]:
print(y)

[2 2 2 1 0 0 1 0 0 2 1 0 1 1 2 1 2 0 0 2 1 2 2 2 1 1 0 0 0 0 0 2 2 0 2 0 2
 0 0 2 1 2 1 1 0 1 1 0 2 0 2 0 0 2 1 0 0 0 0 1 1 2 2 1 2 2 2 2 0 0 2 2 1 0
 2 1 0 1 2 1 1 1 1 2 2 0 2 2 0 2 1 1 1 1 2 0 1 0 2 2 1 0 0 1 2 2 0 1 0 2 2
 1 1 1 2 1 2 2 2 1 0 1 0 2 0 2 2 2 0 0 0 1 1 2 1 2 2 0 2 0 2 2 2 0 2 0 1 1
 2 2 1 1 0 2 0 2 1 0 2 2 0 0 2 0 2 1 0 0 0 0 0 0 0 0 1 0 1 0 0 2 1 2 0 2 1
 0 0 2 1 1 2 2 1 0 2 2 1 0 0 0 2 0 2 1 2 2 2 1 1 0 1 0 2 2 0 1 1 1 2 2 2 2
 1 1 2 1 1 0 0 2 0 1 1 2 2 0 0 0 0 1 1 2 1 0 0 2 2 1 0 2 2 1 2 0 2 0 1 1 0
 1 2 1 0 0 0 2 0 0 0 1 2 1 0 0 1 2 2 0 0 1 1 0 1 0 2 1 1 2 1 0 1 1 1 2 2 0
 0 0 2 0 1 0 2 1 2 0 2 1 2 2 0 0 0 1 2 1 2 2 2 1 0 1 0 0 0 0 0 0 1 1 1 2 0
 1 2 2 1 1 1 1 1 0 2 1 1 1 1 0 2 0 2 0 0 1 1 0 1 0 1 1 0 1 2 2 2 2 1 2 2 1
 0 2 1 0 1 1 1 1 2 1 0 1 2 2 1 0 1 1 2 2 1 2 0 1 0 0 2 0 1 1 1 0 1 1 1 2 0
 2]


In [26]:
for i in range(408):
    if y[i]==2:
        print("There is 2 in the ith"+str(i))
    

There is 2 in the ith0
There is 2 in the ith1
There is 2 in the ith2
There is 2 in the ith9
There is 2 in the ith14
There is 2 in the ith16
There is 2 in the ith19
There is 2 in the ith21
There is 2 in the ith22
There is 2 in the ith23
There is 2 in the ith31
There is 2 in the ith32
There is 2 in the ith34
There is 2 in the ith36
There is 2 in the ith39
There is 2 in the ith41
There is 2 in the ith48
There is 2 in the ith50
There is 2 in the ith53
There is 2 in the ith61
There is 2 in the ith62
There is 2 in the ith64
There is 2 in the ith65
There is 2 in the ith66
There is 2 in the ith67
There is 2 in the ith70
There is 2 in the ith71
There is 2 in the ith74
There is 2 in the ith78
There is 2 in the ith83
There is 2 in the ith84
There is 2 in the ith86
There is 2 in the ith87
There is 2 in the ith89
There is 2 in the ith94
There is 2 in the ith98
There is 2 in the ith99
There is 2 in the ith104
There is 2 in the ith105
There is 2 in the ith109
There is 2 in the ith110
There is 2 in th

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
import random 

DATADIR = "Data/Train/"
CATEGORIES = ["Image","Background","Partial"]
Training_Data = []
img_size = 50
X = []
y = []
for categories in CATEGORIES:
    Path = os.path.join(DATADIR,categories) # gives the path to the images; Data/Train/Image or Background
    print(Path)
    class_num = CATEGORIES.index(categories) # numbers the classes
    print(class_num)
    try:
        for img in os.listdir(Path): #gives the images from the path
            img_array = cv2.imread(os.path.join(Path,img),cv2.IMREAD_GRAYSCALE) 
            Training_Data.append([img_array,class_num])
            #plt.imshow(img_array,cmap='gray')
            #plt.show()
            #break
    except Exception as e:
        pass
print(np.array(Training_Data).shape)
random.shuffle(Training_Data) # do it before conversion to array as list is mutable

for features,labels in Training_Data:
    X.append(features)
    y.append(labels)

X = np.array(X).reshape(-1,img_size,img_size,1) # converts it to arrays with shape (number of images,dim of image)
y = np.array(y)
print(X.shape)
X = X/255.0 # this is normaalization of only the images



Data/Train/Image
0
Data/Train/Background
1
Data/Train/Partial
2
(408, 2)
(408, 50, 50, 1)


In [4]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
import random 

Path = "Data/Test/"
#CATEGORIES = ["Image","Background"]
def test_data():
    #Training_Data = []
    #img_size = 50
    #X = []
    #y = []
    try:
        for img in os.listdir(Path): #gives the images from the path
            #img_array = cv2.imread(os.path.join(Path,img),cv2.IMREAD_GRAYSCALE) 
            #Training_Data.append([img_array,class_num])
            plt.imshow(img_array,cmap='gray')
            plt.show()
            break
    except Exception as e:
            pass
    random.shuffle(Training_Data) # do it before conversion to array as list is mutable
    
    '''
    X = np.array(X).reshape(-1,img_size,img_size,1) # converts it to arrays with shape (number of images,dim of image)
    y = np.array(y)
    print(X.shape)
    X = X/255.0 # this is normaalization of only the images
    '''

    return X,y

X,y = create_training_data()
'''            

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-4-ed8631b2297f>, line 35)

In [57]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
import random  
def Test_Data():
    img_size = 50
    Path = "Data/Test"
    Test = []
    try:
        for img in os.listdir(Path): #gives the images from the path
            img_array = cv2.imread(os.path.join(Path,img),cv2.IMREAD_GRAYSCALE) 
            Test.append(img_array)
            print(img) 
            #plt.imshow(img_array,cmap='gray')
            #plt.show()
            #break
    except Exception as e:
        pass
    Test = np.array(Test).reshape(-1,img_size,img_size,1)
    Test = Test/255.0
    print(Test.shape)
    return Test
t = Test_Data()
#print(t.shape)
print(t[11])

1.tif
9.tif
3.tif
0.tif
4.tif
10.tif
8.tif
6.tif
7.tif
11.tif
2.tif
5.tif
(12, 50, 50, 1)
[[[0.10196078]
  [0.14901961]
  [0.10196078]
  ...
  [0.1372549 ]
  [0.17254902]
  [0.18431373]]

 [[0.07843137]
  [0.04313725]
  [0.11372549]
  ...
  [0.11372549]
  [0.16078431]
  [0.10196078]]

 [[0.18431373]
  [0.09019608]
  [0.18431373]
  ...
  [0.11372549]
  [0.11372549]
  [0.14901961]]

 ...

 [[0.10196078]
  [0.11372549]
  [0.16078431]
  ...
  [0.09019608]
  [0.18431373]
  [0.06666667]]

 [[0.14901961]
  [0.21960784]
  [0.14901961]
  ...
  [0.11372549]
  [0.05490196]
  [0.04313725]]

 [[0.17254902]
  [0.18431373]
  [0.31372549]
  ...
  [0.17254902]
  [0.1372549 ]
  [0.10196078]]]


In [44]:
print(len(y))
print(len(X))

272
272


In [41]:
print(X.shape)
print(X[0:1])

(272, 50, 50, 1)
[[[[0.        ]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.00784314]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.00784314]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  ...

  [[0.00784314]
   [0.        ]
   [0.01960784]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.00784314]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.01960784]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]]]


In [9]:
print(img_array)

[[32 20 44 ... 14 35 20]
 [29 38 47 ... 26 35 17]
 [26 14 53 ... 23 29  8]
 ...
 [14 17 29 ... 38 17 29]
 [11 41 26 ... 23  5 26]
 [38 41 11 ... 14 32 23]]


In [15]:
print(len(Training_Data))

272


In [20]:
import random 
random.shuffle(Training_Data)
for i in Training_Data[:10]:
    print(i[1])

1
0
0
0
1
1
0
0
1
1


In [27]:
X = [] #images or features
y = [] #lables as 0 or 1
img_size = 50
for features,labels in Training_Data:
    X.append(features)
    y.append(labels)
X = np.array(X).reshape(-1,img_size,img_size,1)
print(X.shape)

(272, 50, 50, 1)


In [24]:
print(Training_Data[:1])

[[array([[3, 0, 5, ..., 0, 0, 0],
       [0, 0, 3, ..., 0, 4, 0],
       [0, 2, 0, ..., 0, 0, 1],
       ...,
       [0, 3, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 4, 1]], dtype=uint8), 1]]
